### ISSUE TITLE
A problem about register

### ISSUE THREAD

**Issue by VolcanoWCAN** [kehm/ehrblockchainapplication#3]
I encounter another question
I had modyfied the compose-with-raft.yaml because of the problem I mentioned in https://github.com/kehm/ehrblockchain/issues/4.
networks:
  ehrnetwork:
    external: true
(   ipam:
      config:
        - subnet: 172.18.0.0/24) <-- delete

Then I add 
"docker network create --gateway 172.18.0.1 --subnet 172.18.0.0/24 ehrnetwork_ehrnetwork"

Then  I  restart.

It works when I restart the network.

This time I had start the network successfully.

I add mappings to /etc/hosts.

And then I enroll the application.  However,  it outputs that：

23.02.13: ERROR: An enrollment error occured
23.02.28: Enrolled as 'admin' with 'hospital1.surgery'
23.02.30: Channel 'providerschannel'. Length: 5
23.02.40: Assembling transaction...
**23.02.40: Transaction failed**
![image](https://user-images.githubusercontent.com/33406143/74947143-61db8e00-5435-11ea-801f-f7379509cb9f.png)

The log outputs：
DEBUG ServiceDiscovery - Channel providerschannel peer Peer{ id: 2, name: peer0.hospital1.example.com, channelName: providerschannel, url: grpcs://172.18.0.40:7051} completed chaincode query request
ERROR ServiceDiscovery - Error failed constructing descriptor for chaincodes:<name:"RecordRelationshipContract" > 
**WARN  ServiceDiscovery - Channel providerschannel failed to find all layouts for chaincodes. Expected: 1 and found: 0**

I'm looking for your help!  Thank you !

**Comment by kehm** [comment]
I'm not familiar with the error message, but some possible causes I can think of are:
-Something went wrong during chaincode instantiation (check docker logs).
-Invalid certificates for the discovery peer.

Run "docker ps" to check if all chaincode containers are running correctly, and then run "docker logs [chaincode-container-name]" to check the logs. Also check the logs of peer containers.

As a longer solution, I suggest you migrate to Fabric Gateway and create a connection profile configuration file (yaml) for assigning the discovery peer. You can find a template here: https://github.com/hyperledger/fabric-gateway-java/blob/master/src/test/java/org/hyperledger/fabric/gateway/connection.yaml
